// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzOYPiP8TCLZLKLCEljH44oUk3eOrsX3c',
    appId: '1:691776544815:web:854daeb85d1c9415d826da',
    messagingSenderId: '691776544815',
    projectId: 'garbagemanagement-cdc4b',
    authDomain: 'garbagemanagement-cdc4b.firebaseapp.com',
    storageBucket: 'garbagemanagement-cdc4b.appspot.com',
    measurementId: 'G-9QWJFEDCJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNc0t9BhXkqjH8dXdxaFPkcW-PoQbgxLQ',
    appId: '1:691776544815:android:33bca0a00a6055b9d826da',
    messagingSenderId: '691776544815',
    projectId: 'garbagemanagement-cdc4b',
    storageBucket: 'garbagemanagement-cdc4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS7yBeOAVWm7UzHYL2TMa1ZD5aVceuKcQ',
    appId: '1:691776544815:ios:1497176a0aade651d826da',
    messagingSenderId: '691776544815',
    projectId: 'garbagemanagement-cdc4b',
    storageBucket: 'garbagemanagement-cdc4b.appspot.com',
    iosBundleId: 'com.example.garbageManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS7yBeOAVWm7UzHYL2TMa1ZD5aVceuKcQ',
    appId: '1:691776544815:ios:6e30b06a0759c6e8d826da',
    messagingSenderId: '691776544815',
    projectId: 'garbagemanagement-cdc4b',
    storageBucket: 'garbagemanagement-cdc4b.appspot.com',
    iosBundleId: 'com.example.garbageManagement.RunnerTests',
  );
}
